---
title: "introduction"
output: rmarkdown::html_vignette
bibliography: jpucdbib.bib
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
This project will create an aggregate set of census districts that 
    covers Japanese census districts at the community level for multiple census 
    years. The basic idea is that while Japanese municipalities merged extensively 
    in the early 2000s and continue to merge, community (cho-oaza) have remained 
    largely unchanged. However, there have been many small boundary changes. Also, 
    some exurban developments have produced more extensive changes. This project 
    takes the naive approach of using shapefiles to determine overlaps and merging 
    districts that overlap more than 1% in either direction. It will cover 
    census years 2000, 2005, 2010, 2015 and possibly 2020. It will also cover 
    economic census years 2009 and 2014.

An early version of this project [@engel2018] was written in a mishmash of SQL 
    Server data, R, Microsoft C#, and Microsoft Geography. An objective of the 
    current project is to redevelop it for the R/Github community include R code 
    whenever possible and shapefiles in geojson format.

# Task 1: Convert original shapefiles to geojson

This package includes shapefiles for local census districts in Ibaraki Prefecture covering 
    the six censuses. These as well as shapefiles for all prefectures can also be downloaded from 
    [e-Stat](https://www.e-stat.go.jp/gis/statmap-search?page=1&type=2&aggregateUnitForBoundary=A&toukeiCode=00200521).

The original shapefiles are in kmz format wrapped in a zip file. The first task is to extract and 
    convert these to geojson.

For details, see [Japan Census Shapefiles](origshapefiles.html).

## Subtask 1.1: Convert original kml file to substitute district id codes for feature names

The original shapefiles have placenames for each placemark (feature), but these are not 
    unique. Extended data for each placemark can be used to create unique ids that can be 
    used to relate shapes in the geojson file to be produced to data in a csv to be produced 
    in subtask 1.2.

## Subtask 1.2: Extract extended data into csv file

# References
